import re 
tokens = [
    ('PALABRA_RESERVADA', r'\b(public|private|class|void|int|double|String|new|nextLine|nextInt|nextDouble|println|if|else|do|while|switch|case|default)\b'),
    ('COMENTARIO', r'//.*'),
    ('OPERADOR_ARITMETICO', r'[\+\-\*/%]'),
    ('OPERADOR_RELACIONAL', r'[<>=!]=?'),
    ('OPERADOR_LOGICO', r'[!&|]{1,2}'),
    ('CARACTER', r'[;,\[\]:(){}.]'),
    ('IDENTIFICADOR', r'\b[a-zA-Z][a-zA-Z0-9]*\b'),
    ('CONSTANTE_ENTERA', r'\b-?[0-9]+\b'),
    ('CONSTANTE_REAL', r'\b-?[0-9]*\.?[0-9]+\b'),
    ('CONSTANTE_STRING', r'["“][^"\n]*["”]'),
    ('NEWLINE', r'\n'),
    ('SKIP', r'[ \t]+'),
    ('COMILLAS_TIPOGRAFICAS', r'[“.*”]'),
    # ('MISMATCH', r'.'),
]
token_regexp = '|'.join('(?P<%s>%s)' % pair for pair in tokens)
# tokens = [
#     ('negative_1', r'\bpublic\b'),
#     ('negative_2', r'\bprivate\b'),
#     ('negative_3', r'\bclass\b'),
#     ('negative_4', r'\bvoid\b'),
#     ('negative_5', r'\bint\b'),
#     ('negative_6', r'\bdouble\b'),
#     ('negative_7', r'\bString\b'),
#     ('negative_8', r'\bnew\b'),
#     ('negative_9', r'\bnextLine\b'),
#     ('negative_10', r'\bnextInt\b'),
#     ('negative_11', r'\bnextDouble\b'),
#     ('negative_12', r'\bprintln\b'),
#     ('negative_13', r'\bif\b'),
#     ('negative_14', r'\belse\b'),
#     ('negative_1', r'\bdo\b'),
#     ('negative_1', r'\bwhile\b'),
#     ('negative_1', r'\bswitch\b'),
#     ('negative_1', r'\bcase\b'),
#     ('negative_1', r'\bdefault\b'),
#     ('negative_1', r'//.*'),
#     ('negative_1', r'[\+\-\*/%]'),
#     ('negative_1', r'[<>=!]=?'),
#     ('negative_1', r'[!&|]{1,2}'),
#     ('negative_1', r'[;,\[\]:(){}.]'),
#     ('negative_1', r'\b[a-zA-Z][a-zA-Z0-9]*\b'),
#     ('negative_1', r'-?\b(3276[0-7]|327[0-6][0-9]|32[0-6][0-9][0-9]|3[0-1][0-9][0-9][0-9]|-[0-9]|[1-9][0-9]*)\b'),
#     ('negative_1', r'\b-?[0-9]*\.?[0-9]+\b'),
#     ('negative_1', r'"[^"\n]*"'),
#     ('negative_1', r'\n'),
#     ('negative_1', r'[ \t]+'),
#     ('negative_1', r'.'),
#     ('negative_1', r'[“”]'),
# ]



